import pygame

# Grid
TILE_SIZE = 20
GRID_WIDTH = 30
GRID_HEIGHT = 20

SCREEN_WIDTH = GRID_WIDTH * TILE_SIZE
SCREEN_HEIGHT = GRID_HEIGHT * TILE_SIZE

FPS = 10

# Colors
COLOR_BG = (10, 10, 10)
COLOR_GRID = (40, 40, 40)
COLOR_SNAKE = (0, 200, 0)
COLOR_FOOD = (200, 30, 30)

pygame.font.init()
DEFAULT_FONT = pygame.font.SysFont("consolas", 20)
